sudo: false
language: c
services:
- xvfb
env:
- PATH=~/racket/bin:$PATH

before_install:
- export DISPLAY=:99.0
- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64- linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/
- export PATH=~/racket/bin:$PATH

install:
- # cat /proc/meminfo
- raco pkg install

script:
- make test

after_script:

notifications:
    slack: grift-compiler:k9oxE7yBAUYy2D51Yywu6CjU