sudo: false

language: c

env:
- PATH=~/racket/bin:$PATH

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/
- export PATH=~/racket/bin:$PATH


install:
- raco make -v main.rkt
- raco make -v tests/main.rkt

script:
- racket tests/main.rkt -s all

after_script: